
services:
  

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/media/config/plex:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Series:/tv
      - /mnt/media/music:/music
    network_mode: host
    dns:
      - 127.0.0.1
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes: 
      - /mnt/media/config/sonarr:/config 
      - /mnt/media/Series:/tv 
      - /mnt/media/Downloads:/downloads
    network_mode: host
    dns:
      - 127.0.0.1
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/media/config/radarr:/config
      - /mnt/media/Downloads:/downloads
      - /mnt/media/Movies:/movies
    network_mode: host
    dns:
      - 127.0.0.1
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/media/config/sabnzbd:/config
      - /mnt/media/Downloads:/downloads
      - /mnt/media/Series:/tv
      - /mnt/media/Movies:/movies
    network_mode: host
    dns:
      - 127.0.0.1
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/media/config/prowlarr:/config
    network_mode: host
    dns:
      - 127.0.0.1
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/media/config/tautulli:/config
      - /mnt/media/config/plex:/plex
    ports:
      - 8181:8181
    network_mode: host
    dns:
      - 127.0.0.1
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400 # Check for updates once a day
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 127.0.0.1
    restart: unless-stopped

  portainer_agent:
    image: portainer/agent
    container_name: portainer_agent
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    dns:
      - 127.0.0.1
    restart: unless-stopped
